name: Cleanup PR DNS Record

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host-keys: ${{ vars.SSH_HOST }}

      - name: Add Host to known_hosts
        run: |
          ssh-keyscan -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Remove DNS Record
        run: |
          SUBDOMAIN="${{ github.head_ref }}--preview.t7lab.com"

          # Find the DNS record
          RECORD=$(ssh github@${{ vars.SSH_HOST }} 'curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${{ vars.CLOUDFLARE_ZONE_ID }}/dns_records?type=A&name='$SUBDOMAIN'" \
            -H "X-Auth-Email: ${{ vars.CLOUDFLARE_EMAIL }}" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
            -H "Content-Type: application/json"')

          RECORD_ID=$(echo "$RECORD" | jq -r '.result[0].id')

          if [ "$RECORD_ID" != "null" ]; then
            # Delete the DNS record
            ssh github@${{ vars.SSH_HOST }} 'curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/${{ vars.CLOUDFLARE_ZONE_ID }}/dns_records/'$RECORD_ID'" \
              -H "X-Auth-Email: ${{ vars.CLOUDFLARE_EMAIL }}" \
              -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
              -H "Content-Type: application/json"'
            echo "Deleted DNS record for $SUBDOMAIN"
          else
            echo "No DNS record found for $SUBDOMAIN"
          fi

      - name: Remove Docker Container
        run: |
          ssh github@${{ vars.SSH_HOST }} "docker stop preview-${{ github.head_ref }} || true && \
          docker rm preview-${{ github.head_ref }} || true"

      - name: Remove caddy Preview site
        run: |
          scp ./scripts/configure_caddy.sh github@${{ vars.SSH_HOST }}:/home/github/configure_caddy.sh
          ssh github@${{ vars.SSH_HOST }} "chmod +x /home/github/configure_caddy.sh && /home/github/configure_caddy.sh ${{ github.head_ref }} 8085 --delete && rm /home/github/configure_caddy.sh"
