name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key for GitHub Actions
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent)
          ssh-add ~/.ssh/id_rsa

      - name: Deploy Docker Container
        run: |
          ssh root@88.198.127.216 "docker run -d --name preview-${{ github.head_ref }} -p 800${{ github.run_number }}:80 my-app-image"

      - name: Configure NGINX for Preview
        run: |
          ssh root@88.198.127.216 "bash /home/phil/scripts/nginx_configure.sh ${{ github.head_ref }} 800${{ github.run_number }}"

      - name: Add DNS Record in Cloudflare
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          zoneId: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          cloudflare-cli dns create --type A --name "${{ github.head_ref }}.preview.t7lab.com" --content "<your-hetzner-ip>" --proxied true
